import assert from 'node:assert/strict';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),{chromium}=require(path.join(process.env.DASHBOARD_QA_NODE_MODULES,'playwright'));
const base=process.env.DASHBOARD_QA_URL||'http://127.0.0.1:8089';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE});
let admin;
try{
 const context=await browser.newContext({viewport:{width:1600,height:1050}}),page=await context.newPage();
 const errors=[],external=[];let state,hello;
 await context.route('**/*',async route=>{if(new URL(route.request().url()).origin!==base){external.push(route.request().url());await route.abort();}else await route.continue();});
 page.on('pageerror',error=>errors.push(error.message));
 page.on('websocket',socket=>socket.on('framereceived',({payload})=>{if(typeof payload==='string'){const value=JSON.parse(payload);if(value.type==='state')state=value;if(value.type==='hello')hello=value;}}));
 await page.goto(base+'/admin.html');await page.waitForFunction(()=>document.querySelectorAll('#robot-rows tr').length===6);
 admin=new WebSocket(base.replace('http','ws')+'/ws?role=admin');await new Promise(resolve=>admin.onopen=resolve);
 if(state.run.state!=='IDLE'){admin.send(JSON.stringify({cmd:'reset'}));await page.waitForFunction(()=>document.querySelector('#run-state').textContent==='IDLE');}
 await page.waitForFunction(()=>document.querySelectorAll('#fleet-editor tbody tr').length===14);
 assert.equal(await page.locator('#fleet-editor').getAttribute('open'),null);
 assert.equal(await page.locator('#robot-rows tr').count(),6);
 assert.equal(await page.locator('#checklist details').evaluateAll(rows=>rows.filter(row=>row.dataset.group.startsWith('spare_')).length),0);
 await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:'dashboard/REPORTS/img/M6_admin_default_six.png',fullPage:true});
 const before=await (await page.request.get(base+'/api/admin')).json(),original={...before.roster};
 const role=hello.drones[1],physical=before.fleet.drones.find(item=>!Object.values(original).includes(item.id)).id;
 await page.locator('#fleet-editor summary').click();
 await page.locator(`select[aria-label="${physical} 역할"]`).selectOption(role);
 await page.getByRole('button',{name:'배정 검토',exact:true}).click();
 assert.equal(await page.locator('dialog').getAttribute('open'),'');
 assert.match(await page.locator('dialog pre').textContent(),new RegExp(original[role]+' → '+physical));
 const notSaved=await (await page.request.get(base+'/api/admin')).json();assert.deepEqual(notSaved.roster,original);
 await page.screenshot({path:'dashboard/REPORTS/img/M6_roster_confirm.png',fullPage:true});
 await page.getByRole('button',{name:'배정 저장',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('#stack-panel').textContent.includes('배정 저장 완료'));
 await page.waitForFunction(()=>!document.querySelector('[data-cmd="preflight"]').disabled);
 assert.equal((await (await page.request.get(base+'/api/admin')).json()).roster[role],physical);
 await page.waitForTimeout(150);
 assert.notEqual(state.stack.roster_hash,state.stack.applied_hash);
 assert.equal(state.robots[role].fleet_id,physical);
 assert.ok(state.checklist.some(row=>row.id==='global.roster'&&!row.ok&&row.blocking));
 await page.screenshot({path:'dashboard/REPORTS/img/M6_roster_restart_needed.png',fullPage:true});
 await page.getByRole('button',{name:'스택 재기동',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.stack-summary').textContent.includes('배정 일치'));
 assert.equal(state.stack.roster_hash,state.stack.applied_hash);
 await page.locator('[data-cmd="preflight"]').click();await page.waitForFunction(()=>document.querySelector('#run-state').textContent==='READY');
 assert.equal(await page.locator('#fleet-editor select:enabled').count(),0);
 const blocked=await page.request.put(base+'/api/fleet/roster',{data:{roster:original}});assert.equal(blocked.status(),409);
 await page.locator('[data-cmd="reset"]').click();await page.waitForFunction(()=>document.querySelector('#run-state').textContent==='IDLE');
 const restore=await page.request.put(base+'/api/fleet/roster',{data:{roster:original}});assert.equal(restore.status(),200);
 const restart=await page.request.post(base+'/api/fleet/restart');assert.equal(restart.status(),200);
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);
 console.log('PASS M6 actualmock: six default role rows, spare checks hidden, collapsed14 inventory, draft unsaved, review dialog, save/reconnect/physicalreplacement, hash blocks, restart matches, READY UI+HTTP reject, originalmockroster restored; pageerrors0 external0');
}finally{admin?.close();await browser.close();}
